### ISSUE TITLE
System.InvalidOperationException: You can only set the base cache path once before using the Barrel.

### ISSUE THREAD

**Issue by iamheiner** [jamesmontemagno/monkey-cache#82]
I am using **MonkeyCache.FileStore**, I have declared **BarrelUtils.SetBaseCachePath** in the App constructor but randomly when I start the application I get the error

 `System.InvalidOperationException: You can only set the base cache path once before using the Barrel.`

Is it correct to declare **BarrelUtils.SetBaseCachePath** in the  App constructor or should it go somewhere else?

![image](https://user-images.githubusercontent.com/6698728/80532549-a0914580-899c-11ea-8c86-cc20b0801044.png)

**Comment by jamesmontemagno** [comment]
I would create a singleton pattern such as: https://github.com/jamesmontemagno/app-ac-islandtracker/blob/master/TurnipTracker/Services/DataService.cs

**Comment by iamheiner** [comment]
Great, I've implemented the singleton method and so far I haven't had this mistake. Thank you very much for the example.

**Comment by pmasonuh** [comment]
Hi @iamheiner, would you please share sample code on how you implemented the singleton.  I took a look at the link above, but I am still not clear one what needs to be done.  I understand the singleton pattern, but something is not clicking for me.

Thanks.

**Comment by pmasonuh** [comment]
I was going to go a different route and set a bool in my localSettings, but I ran across the following:

if (Application.Current.Properties.ContainsKey("FirstUse"))

I will give this a try, but still look forward to hearing back from you.

Thanks.
